android.builder.sdkDownload=false
android.buildToolsVersion=34.0.0
android.compileSdkVersion=34
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
kotlin.code.style=official
org.gradle.caching=true
